//! Remote theme gallery — fetches the published index of themes so the
//! user can install them in-app. The index is a single JSON file
//! (assets/themes/index.json in the repo, regenerated by CI) with full
//! ThemeDefs embedded, so one request gets everything: preview data and
//! the palette to write on install. No per-theme download, no GitHub
//! API rate limits.

use serde::Deserialize;

use super::def::ThemeDef;

const INDEX_URL: &str =
    "https://raw.githubusercontent.com/schizza/snapdash/dev/assets/themes/index.json";

#[derive(Debug, Deserialize)]
struct Index {
    #[allow(dead_code)]
    schema: u32,
    themes: Vec<ThemeDef>,
}

/// Fetch the published theme index.
pub fn fetch_index() -> Result<Vec<ThemeDef>, String> {
    let bytes = reqwest::blocking::Client::builder()
        .user_agent("snapdash")
        .build()
        .map_err(|e| format!("http client: {e}"))?
        .get(INDEX_URL)
        .send()
        .map_err(|e| format!("fetch index: {e}"))?
        .error_for_status()
        .map_err(|e| format!("index http error: {e}"))?
        .bytes()
        .map_err(|e| format!("read index: {e}"))?;

    let index: Index = serde_json::from_slice(&bytes).map_err(|e| format!("parse index: {e}"))?;

    Ok(index.themes)
}
