name: Release Drafter

on:
  push:
    branches: [dev]
  pull_request:
    types: [opened, reopened, synchronize, edited, labeled, unlabeled]
    branches: [dev, main]

permissions:
  contents: write
  pull-requests: write

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
